name: Cleanup GitHub Pages

on:
  workflow_dispatch:

jobs:
  cleanup-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Remove all files except .git
        run: |
          shopt -s extglob
          rm -rf !(.git)

      - name: Commit and push cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Clean up GitHub Pages content" || echo "Nothing to commit"
          git push origin gh-pages
          