name: Cleanup GitHub Pages

on:
  workflow_dispatch:

jobs:
  cleanup-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Delete all files
        run: |
          git rm -rf . || true
          rm -rf ./* .[^.]* || true
          echo "Cleanup on $(date)" > README.md
          git add README.md

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Cleaned up gh-pages branch" || echo "Nothing to commit"
          git push origin gh-pages
          