name: Deploy Acceptance Test Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate Index Page
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifact-index
          echo "<html><body><h1>Acceptance Test Artifacts</h1>" > artifact-index/index.html

          # Get all artifacts and combine them into a single array
          gh api --paginate /repos/${{ github.repository }}/actions/artifacts | \
          jq -s 'add | .artifacts[] | select(.name == "report-folder" and .expired == false) | {name, branch: .workflow_run.head_branch, id: .id, archive_download_url}' | \
          jq -s 'group_by(.branch) | .[] as $branch_group | "<h2>Branch: \($branch_group[0].branch)</h2><ul>" + ($branch_group | map("<li><a href=\"" + .archive_download_url + "\">Artifact #\(.id)</a></li>") | join("")) + "</ul>"' >> artifact-index/index.html

          echo "</body></html>" >> artifact-index/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact-index

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
