name: Deploy Playwright Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: report-folder
          path: playwright-report/  # change if your report is in a different folder

  deploy-to-pages:
    needs: test-and-upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download Playwright report
        uses: actions/download-artifact@v4
        with:
          name: report-folder
          path: root-webapp/latest-report

      - name: Generate index.html
        run: |
          echo "<html><head><title>Acceptance Test Reports</title></head><body>" > root-webapp/index.html
          echo "<h1>Acceptance Test Reports</h1>" >> root-webapp/index.html
          echo "<a href='latest-report/index.html'>Latest Test Report</a><br>" >> root-webapp/index.html
          echo "</body></html>" >> root-webapp/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: root-webapp

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        