name: Deploy Acceptance Test Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

jobs:
  deploy-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install jq unzip -y
          gh auth setup-git

      - name: Fetch and extract artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p root-webapp
          
          # Get latest 50 artifacts named 'report-folder' from 'gh-pages-5.yml'
          gh api --paginate /repos/${{ github.repository }}/actions/artifacts | \
          jq -r '[.artifacts[] 
            | select(.name == "report-folder" and .expired == false)
            | {id, name, created_at, archive_download_url, run_id}] 
            | sort_by(.created_at) 
            | reverse 
            | .[:50]' > artifacts.json

          # For each artifact: download, extract to folder: root-webapp/<branch>/<timestamp-runId>/
          cat artifacts.json | jq -c '.[]' | while read artifact; do
            ID=$(echo "$artifact" | jq -r '.id')
            RUN_ID=$(echo "$artifact" | jq -r '.run_id')
            CREATED=$(echo "$artifact" | jq -r '.created_at' | sed 's/[:T]/-/g' | cut -d'.' -f1)
            
            # Get branch from run metadata
            RUN_DATA=$(gh api /repos/${{ github.repository }}/actions/runs/$RUN_ID)
            BRANCH=$(echo "$RUN_DATA" | jq -r '.head_branch')

            FOLDER="root-webapp/${BRANCH}/${CREATED}_run-${RUN_ID}"
            mkdir -p "$FOLDER"
            
            gh api -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository }}/actions/artifacts/$ID/zip -q > tmp.zip

            unzip -q tmp.zip -d "$FOLDER"
            rm tmp.zip
          done

      - name: Generate index.html
        run: |
          echo "<html><body><h1>Acceptance Test Reports</h1>" > root-webapp/index.html
          for branch in $(ls root-webapp); do
            [ "$branch" == "index.html" ] && continue
            echo "<h2>$branch</h2><ul>" >> root-webapp/index.html
            for report in $(ls root-webapp/$branch); do
              echo "<li><a href=\"./$branch/$report/index.html\">$report</a></li>" >> root-webapp/index.html
            done
            echo "</ul>" >> root-webapp/index.html
          done
          echo "</body></html>" >> root-webapp/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: root-webapp

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        