name: Deploy Test Reports - 2

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Set up Pages
        uses: actions/configure-pages@v4

      - name: Fetch and extract latest artifacts per branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p _site
          REPO="${GITHUB_REPOSITORY}"

          echo "Fetching all non-expired 'acceptance-test-results' artifacts..."
          gh api --paginate "/repos/${REPO}/actions/artifacts" \
            | jq -r '.artifacts[] | select(.name=="acceptance-test-results" and .expired==false) | "\(.workflow_run.head_branch) \(.id) \(.created_at) \(.archive_download_url)"' \
            | sort -k1,1 -k3,3r \
            | awk '!seen[$1]++' \
            | while read -r BRANCH ARTIFACT_ID CREATED_AT DOWNLOAD_URL; do
                TIMESTAMP=$(date -d "$CREATED_AT" +"%Y%m%d%H%M%S")
                DEST_DIR="_site/${BRANCH}/${TIMESTAMP}"
                mkdir -p "$DEST_DIR"
                echo "Processing artifact for branch '$BRANCH' created at '$CREATED_AT'..."
                curl -L -H "Authorization: token $GH_TOKEN" "$DOWNLOAD_URL" -o artifact.zip
                unzip -q artifact.zip -d "$DEST_DIR"
                rm artifact.zip
              done

      - name: Generate index.html
        run: |
          INDEX_FILE="_site/index.html"
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Acceptance Test Reports</title></head><body>" > "$INDEX_FILE"
          echo "<h1>Acceptance Test Reports</h1>" >> "$INDEX_FILE"
          for BRANCH_DIR in _site/*/; do
            BRANCH=$(basename "$BRANCH_DIR")
            echo "<h2>Branch: $BRANCH</h2><ul>" >> "$INDEX_FILE"
            for REPORT_DIR in "$BRANCH_DIR"*/; do
              TIMESTAMP=$(basename "$REPORT_DIR")
              echo "<li><a href='${BRANCH}/${TIMESTAMP}/'>${TIMESTAMP}</a></li>" >> "$INDEX_FILE"
            done
            echo "</ul>" >> "$INDEX_FILE"
          done
          echo "</body></html>" >> "$INDEX_FILE"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
