name: Display Test Reports

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup basic site
        run: |
          # Create site directory
          mkdir -p _site
          
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y jq curl unzip
          
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh
          
          # Get artifact data using GitHub CLI
          REPO="${GITHUB_REPOSITORY}"
          echo "Fetching artifacts from $REPO"
          gh api --paginate "/repos/$REPO/actions/artifacts" > artifacts.json
          
          # Create simple index.html
          cat > _site/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Reports</title>
            <style>
              body { font-family: sans-serif; margin: 20px; }
              h1 { color: #0366d6; }
              pre { background: #f6f8fa; padding: 10px; border-radius: 5px; }
            </style>
          </head>
          <body>
            <h1>Test Reports</h1>
            <p>View the latest artifacts directly in the GitHub Actions tab.</p>
            <p><a href="https://github.com/${GITHUB_REPOSITORY}/actions">Go to GitHub Actions</a></p>
          </body>
          </html>
          EOL
          
          # Create a tarball for deployment
          tar -czf ../site.tar.gz -C _site .

      - name: Configure Pages
        uses: actions/configure-pages@v4
          
      # Use actions/upload-pages-artifact@v3 instead of v2
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site.tar.gz

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        