
# trying with github actions

name: Deploy Playwright Reports to GitHub Pages

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  deploy-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq unzip

      - name: Fetch and unpack Playwright test artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p root-webapp

          # Fetch all artifacts
          gh api --paginate /repos/${{ github.repository }}/actions/artifacts | \
            jq -c '.artifacts[] | select(.name == "report-folder" and .expired == false)' | \
            while read artifact; do
              ID=$(echo "$artifact" | jq -r '.id')
              CREATED=$(echo "$artifact" | jq -r '.created_at' | sed 's/[:T]/-/g' | cut -d'.' -f1)
              RUN_ID=$(echo "$artifact" | jq -r '.workflow_run.id')

              CREATED=${CREATED:-"unknown-time"}
              RUN_ID=${RUN_ID:-"unknown-run"}

              FOLDER="root-webapp/${CREATED}_run-${RUN_ID}"
              mkdir -p "$FOLDER"

              DOWNLOAD_URL=$(echo "$artifact" | jq -r '.archive_download_url')
              curl -sSL -H "Authorization: token $GITHUB_TOKEN" "$DOWNLOAD_URL" -o tmp.zip
              unzip -q tmp.zip -d "$FOLDER"
              rm tmp.zip
          done

      - name: Generate index.html for the reports
        run: |
          echo "<html><head><title>Playwright Test Reports</title></head><body><h1>Playwright Test Reports</h1>" > root-webapp/index.html
          for dir in root-webapp/*_run-*; do
            NAME=$(basename "$dir")
            echo "<a href=\"$NAME/index.html\">$NAME</a><br>" >> root-webapp/index.html
          done
          echo "</body></html>" >> root-webapp/index.html

      - name: Generate history.html page with links to all reports
        run: |
          echo "<html><head><title>Test History</title></head><body><h1>Test History</h1>" > root-webapp/history.html
          echo "<p>Here are all previous test reports:</p>" >> root-webapp/history.html
          for dir in root-webapp/*_run-*; do
            NAME=$(basename "$dir")
            echo "<a href=\"$NAME/index.html\">$NAME</a><br>" >> root-webapp/history.html
          done
          echo "</body></html>" >> root-webapp/history.html

      - name: Configure git user for deploying to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          # Set up the gh-pages branch for deployment
          git checkout --orphan gh-pages
          git rm -rf .
          cp -R root-webapp/* .
          git add .
          git commit -m "Deploy Playwright reports"
          git push --force origin gh-pages

