name: Display Test Reports

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup basic site
        env:
          GH_TOKEN: ${{ github.token }}  # This is the key fix
        run: |
          # Create site directory
          mkdir -p _site
          
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y jq curl unzip
          
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh
          
          # Get artifact data using GitHub CLI
          REPO="${GITHUB_REPOSITORY}"
          echo "Fetching artifacts from $REPO"
          gh api --paginate "/repos/$REPO/actions/artifacts" > artifacts.json
          
          # Process artifacts data to get only non-expired report-folder artifacts
          jq '[.artifacts[] | select((.name=="report-folder") and (.expired==false))]' artifacts.json > filtered.json
          jq 'sort_by(.created_at) | reverse | .[0:50]' filtered.json > latest.json
          jq 'group_by(.workflow_run.head_branch)' latest.json > grouped.json
          
          # Create a simple index listing the artifacts
          echo "<html><head><title>Test Reports</title></head><body>" > _site/index.html
          echo "<h1>Test Reports</h1>" >> _site/index.html
          echo "<p>Available artifacts:</p><pre>" >> _site/index.html
          cat grouped.json >> _site/index.html
          echo "</pre></body></html>" >> _site/index.html

      - name: Configure Pages
        uses: actions/configure-pages@v4
          
      # Use actions/upload-pages-artifact@v3 instead of v2
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        