name: Deploy Reports - 2

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-reports"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download artifacts and generate index
        env:
          GH_TOKEN: ${{ github.token }}
          TARGET_ARTIFACT_NAME: "acceptance-test-results"
        run: |
          mkdir -p _site
          REPO="${GITHUB_REPOSITORY}"

          echo "Fetching recent successful runs..."
          gh api "/repos/${REPO}/actions/runs" --paginate -q \
            '.workflow_runs[] | select(.conclusion=="success") | {id, head_branch}' \
            | jq -s 'sort_by(.id) | reverse | .[:10]' \
            | jq -c '.'[] \
            | while read -r RUN; do
              RUN_ID=$(echo "$RUN" | jq -r '.id')
              BRANCH=$(echo "$RUN" | jq -r '.head_branch')
              echo "Checking run $RUN_ID for branch $BRANCH..."

              gh api "/repos/${REPO}/actions/runs/${RUN_ID}/artifacts" > artifacts.json
              ARTIFACT=$(jq -c ".artifacts[] | select(.name == \"${TARGET_ARTIFACT_NAME}\")" artifacts.json)

              if [ ! -z "$ARTIFACT" ]; then
                ARTIFACT_URL=$(echo "$ARTIFACT" | jq -r '.archive_download_url')
                mkdir -p "_site/${BRANCH}"
                echo "Downloading and extracting artifact..."
                gh api "$ARTIFACT_URL" --method GET > artifact.zip
                unzip -o artifact.zip -d "_site/${BRANCH}" && rm artifact.zip
              fi
            done

          # Generate index.html
          cat > _site/index.html <<EOF
          <!DOCTYPE html>
          <html><head><meta charset="UTF-8"><title>Acceptance Test Reports</title></head><body>
          <h1>Acceptance Test Reports</h1>
          EOF

          find _site -mindepth 1 -maxdepth 1 -type d | while read dir; do
            BRANCH=$(basename "$dir")
            echo "<h2>Branch: $BRANCH</h2><ul>" >> _site/index.html
            for file in "$dir"/*; do
              NAME=$(basename "$file")
              echo "<li><a href=\"${BRANCH}/${NAME}\">${NAME}</a></li>" >> _site/index.html
            done
            echo "</ul>" >> _site/index.html
          done

          echo "</body></html>" >> _site/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
